spring:
  application:
    name: account
  redis-cache:
    port: 6379
    host: localhost
    database: 0
    timeout: 2000
    enable: true
    pool:
      max-idle: 50
      min-idle: 10
      max-total: 50